import type { HudState } from "@/lib/hud-api";

/** Dev-only fixture so the MOAP layout can be screenshot without the SL API. */
export const LAYOUT_PREVIEW_STATE: HudState = {
  user: { name: "Aria Resident", avatarKey: "preview", role: "mom" },
  pregnancy: {
    id: "preview",
    status: "pregnant",
    week: 22,
    day: 0,
    trimester: 2,
    progressPct: 55,
    dueDate: "2026-09-14",
    daysToGo: 18,
    delivered: false,
    babyName: "Peach",
    babyGender: "surprise",
    durationDays: 280,
    setupComplete: true,
    setupStep: 0,
    progressionMode: "realtime",
    babyCount: 1,
    babyNames: ["Peach"],
    privacyMode: "partner",
    labor: {
      stage: "none",
      phase: "none",
      inLabor: false,
      hospitalAdvised: false,
      minutesToBirth: null,
      intensity: 0,
      waterBroken: false,
      atHospital: false,
      contractionMinutes: 0,
      waterBrokenAt: null,
      contractionsStartedAt: null,
      hospitalAt: null,
      birthAt: null,
    },
    baby: {
      size: "Papaya",
      lengthCm: 30.1,
      weightG: 600,
      note: "Baby is getting stronger every day.",
      heartbeat: 142,
      kicksToday: 12,
      position: "Head down",
      movement: "Active",
      wellness: 82,
      bond: 74,
      movementScore: 68,
    },
  },
  stats: {
    energy: 62,
    hydration: 58,
    hunger: 65,
    bladder: 40,
    mood: 75,
    immunity: 70,
    sickness: 22,
    rest: 55,
    vitamins: 48,
    comfort: 60,
    nutrition: 64,
    stress: 28,
    baby_wellness: 82,
    baby_bond: 74,
    baby_movement: 68,
  },
  mood: {
    key: "glowing",
    label: "Glowing",
    emoji: "✨",
    note: "Soft and hopeful.",
    hint: "A quiet, happy day with baby.",
  },
  wellness: 68,
  symptoms: [
    { name: "Back Pain", severity: 30, label: "Mild" },
    { name: "Fatigue", severity: 50, label: "Moderate" },
    { name: "Headache", severity: 0, label: "None" },
    { name: "Heartburn", severity: 28, label: "Mild" },
    { name: "Nausea", severity: 45, label: "Moderate" },
  ],
  journal: [
    {
      id: "j1",
      title: "First kicks",
      body: "Felt a little flutter.",
      kind: "milestone",
      completed: true,
      entry_date: "2026-08-01",
      created_at: "2026-08-01T12:00:00.000Z",
    },
  ],
  partner: {
    name: "Alex Parker",
    linked: true,
    code: "NEST12",
    support: 84,
    pendingLinks: [],
    permissions: null,
    activities: [
      {
        actor_name: "Alex Parker",
        activity: "Brought water",
        created_at: "2026-08-30T18:00:00.000Z",
      },
    ],
  },
  notifications: [
    {
      id: "n1",
      title: "Drink some water",
      body: "Hydration is a little low.",
      read: false,
      created_at: "2026-08-31T16:00:00.000Z",
    },
  ],
  unread: 1,
  currentCraving: null,
  ultrasounds: [],
  newUltrasounds: 0,
  foods: [],
  recentEvents: [],
  requests: { incoming: [], outgoing: [] },
  hospitalBag: null,
  milestones: [],
  sharedEvents: [],
  popupFrequencyMinutes: 20,
  nextEventAt: null,
  settings: {},
  serverTime: new Date().toISOString(),
};
